version: '2'
services:
  db:
    image: de1m0s/postgres-compose:1.0
    container_name: tomcat-db-container
    environment:
      POSTGRES_PASSWORD: tomcat_password
      POSTGRES_USER: tomcat_user
      POSTGRES_DB: tomcat_db
  web-server:
    image: de1m0s/tomcat-compose:1.1
    environment:
      TOMCAT_DB_NAME: tomcat_db
      TOMCAT_DB_USER: tomcat_user
      TOMCAT_DB_PASSWORD: tomcat_password
      TOMCAT_DB_HOST: db
    ports:
      - "8001:8080"
    links:
      - db
  nginx-proxy:
    image: de1m0s/nginx-compose:1.3
    environment:
      NGINX_HOST: localhost
      NGINX_PORT: 80
      NGINX_PROXY_HOST: web-server
      NGINX_PROXY_PORT: 8080
      NGINX_STATIC_FOLDER: /var/data/
    volumes:
      - /home/denis/Projects/DutchTreat/Client/app:/var/data
    ports:
      - "80:80"
    links:
      - web-server
